public class KYCAccountDetails {
public String accName;
public String accNumber;
public String kycId;
public String billingStreet;
public String billingCity;
public String BillingState;
public String billingPostalCode;
public String billingCountry;
public Decimal sic_codes;
public String companyStatus;
public String ownership;
public String LegalEntity;
public String LegalEntiyId;
public String RegAddressRoad;
public String RegAddressPremises;
}